apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lab-backend:1.0
        ports:
        - containerPort: 5000
        imagePullPolicy: Never #usa la imagen de mi maquina local
